### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by jonny-improbable** [konsumer/node-protoc-plugin#1]
Hello 👋

I am one of the maintainers of [improbable-eng/grpc-web](https://github.com/improbable-eng/grpc-web) and [improbable-eng/ts-protoc-gen](https://github.com/improbable-eng/ts-protoc-gen). I am interested in integrating protoc-gen into our toolchain but the lack of TypeScript definitions is currently blocking this. I currently see two path forward:

1. Convert this project (node-protoc-plugin) to be written in TypeScript
2. Create (and maintain) an independent set of TypeScript definitions as part of the DefinitelyTyped repo.

Option 1 would be my preference as it's easier to maintain (option 2 can easily result in the definitions going out of sync with this package) - I'd be happy to put in the work (raise the PR) to convert the project; however this clearly has implications on your project :)

Please let me know your thoughts, and thanks for creating this project.

**Comment by jonny-improbable** [comment]
Given the lack of input, I've gone for option number 2 and raised a PR to add an `@type/protoc-plugin` against the DefinitelyTyped repo [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33805).

**Comment by konsumer** [comment]
Sorry, I was very busy and missed this.

I don't personally use typescript, so for me I think it might not be worth it for something I wouldn't use. Are the definitions something that could just be auto-generated from the node code, or generated from some other less-intrusive method? In that case, I'd be happy to add annotation/comments/definition-files or something. "Change the programming language of your project" seems like a large ask (like maybe a seperate project makes most sense.)
